
[config:base]
; Copy ini_use_config value to Marlin/config.ini to use
;ini_use_config                          = basic
;                                            +linear_advance
;                                            +host
;                                            @../config/examples/NoviS3D/nano_config.ini
ini_config_version                       = 02010300
string_config_h_author                   = "qw3rtrun"
config_examples_dir                      = "config/examples/NoviS3D"

[config:basic]
# MOTHERBOARD and MCU capabilities
CUSTOM_MACHINE_NAME                      = "Novi Sad 3D Printer (Nano)"
motherboard                              = BOARD_MKS_ROBIN_NANO_V3_1
serial_port                              = 1
baudrate                                 = 115200
serial_port_2                            = 2
baudrate_2                               = 115200
sdsupport                                = on
eeprom_settings                          = on
eeprom_auto_init                         = on
eeprom_init_now                          = on
disable_M503                             = off

# MACHINE MECHANICS and STEPPERS
x_bed_size                               = 170
y_bed_size                               = 200
z_max_pos                                = 200
x_min_pos                                = 0
x_max_pos                                = X_BED_SIZE
y_min_pos                                = 0
y_max_pos                                = Y_BED_SIZE
z_min_pos                                = 0

default_nominal_filament_dia             =
default_axis_steps_per_unit              = { 80, 80, 400, 1140 }
default_max_acceleration                 = { 2000, 3000, 1000, 8000 }
DEFAULT_ACCELERATION                     = 2000
DEFAULT_RETRACT_ACCELERATION             = 2000
DEFAULT_TRAVEL_ACCELERATION              = 2000
default_max_feedrate                     = { 200, 200, 100, 70 }
homing_feedrate_mm_m                     = { (60*60), (60*60), (30*60) }

x_driver_type                            = A4988
invert_x_dir                             = true
y_driver_type                            = A4988
invert_y_dir                             = true
z_driver_type                            = A4988
invert_z_dir                             = true
e0_driver_type                           = A4988
invert_e0_dir                            = true

endstoppullups                           = on
x_max_endstop_hit_state                  = LOW
x_min_endstop_hit_state                  = LOW
y_max_endstop_hit_state                  = LOW
y_min_endstop_hit_state                  = LOW
z_max_endstop_hit_state                  = LOW
z_min_endstop_hit_state                  = LOW

#SOWFTWARE ENDSTOPS
max_software_endstops                    = on
max_software_endstop_x                   = on
max_software_endstop_y                   = on
max_software_endstop_z                   = on
min_software_endstops                    = on
min_software_endstop_x                   = on
min_software_endstop_y                   = on
min_software_endstop_z                   = on

# HOMING
x_home_dir                               = -1
z_home_dir                               = -1
y_home_dir                               = -1
z_after_homing                           = 10
z_clearance_for_homing                   = 4
z_min_probe_endstop_hit_state            = Z_MIN_ENDSTOP_HIT_STATE
homing_bump_mm                           = { 0, 0, 5 }
HOMING_BUMP_DIVISOR                      = { 3, 3, 5 }

# FANS
e0_auto_fan_pin                          = -1
extruder_auto_fan_speed                  = 255
extruder_auto_fan_temperature            = 50

# EXTRUDERS and TEMPERATURE CONTROL
extruders                                = 1
temp_sensor_0                            = 5
thermal_protection_hotends               = on
heater_0_mintemp                         = 5
heater_0_maxtemp                         = 261
extrude_mintemp                          = 189
prevent_cold_extrusion                   = on
max_heater_0_power                       = 224
bang_max                                 = MAX_HEATER_0_POWER
pidtemp                                  = on
pid_k1                                   = 0.95
pid_max                                  = MAX_HEATER_0_POWER
default_kp                               = 22.22
default_ki                               = 3.04
default_kd                               = 33.62

# BED HEATING
temp_sensor_bed                          = 4
thermal_protection_bed                   = on
bed_mintemp                              = 5
bed_maxtemp                              = 100
max_bed_power                            = 192
pidtempbed                               = on
default_bedKp                            = 83.98
default_bedKi                            = 16.12
default_bedKd                            = 291.68

# PREHEATS
preheat_1_label                          = "PLA"
preheat_1_temp_bed                       = 70
preheat_1_temp_hotend                    = 180
preheat_2_label                          = "ABS"
preheat_2_temp_bed                       = 110
preheat_2_temp_hotend                    = 240

[config:host]
host_action_commands                     = on
emergency_parser                         = on
faster_gcode_parser                      = on
GCODE_QUOTED_STRINGS                     = on
gcode_case_insensitive                   = on
BINARY_FILE_TRANSFER                     = on
advanced_ok                              = on
host_keepalive_feature                   = on
default_keepalive_interval               = 2
serial_overrun_protection                = on
auto_report_position                     = on
auto_report_temperatures                 = on
extended_capabilities_report             = on
bufsize                                  = 4
tx_buffer_size                           = 128
block_buffer_size                        = 16
max_cmd_size                             = 96

[config:linear]
lin_advance                              = on
advance_k                                = 0.05
distinct_e_factors                       = off
volumetric_extruder_limit                = off
classic_jerk                             = off
default_ejerk                            = 5.0
