
[config:base]
; Copy ini_use_config value to Marlin/config.ini to use
;ini_use_config                          = basic
;                                            +easythreed_ui
;                                            +linear_advance
;                                            +backlash
;                                            +host
;                                            @../config/examples/EasyThreeD/ET4000PLUS/config.ini
ini_config_version                       = 02010300
string_config_h_author                   = "qw3rtrun"
config_examples_dir                      = "config/examples/EasyThreeD/ET4000PLUS"

[config:basic]
# MOTHERBOARD and MCU capabilities
CUSTOM_MACHINE_NAME                      = "EasyThread K9"
motherboard                              = BOARD_MKS_ROBIN_LITE
serial_port                              = 1
baudrate                                 = 115200
serial_port_2                            = off
;serial_port_2                            = 2
;baudrate_2                               = 250000
sdsupport                                = on
eeprom_settings                          = on
eeprom_auto_init                         = on
eeprom_init_now                          = on
disable_M503                             = off

# MACHINE MECHANICS and STEPPERS
x_bed_size                               = 100
y_bed_size                               = 100
z_max_pos                                = 100
x_min_pos                                = 0
x_max_pos                                = X_BED_SIZE
y_min_pos                                = 0
y_max_pos                                = Y_BED_SIZE
z_min_pos                                = 0

default_nominal_filament_dia             = 1.75
default_axis_steps_per_unit              = { 606, 606, 606, 1140 }
default_max_acceleration                 = { 300, 300, 300, 10000 }
default_max_feedrate                     = { 100, 100, 100, 70 }
homing_feedrate_mm_m                     = { (60*60), (60*60), (30*60) }

x_driver_type                            = A4988
invert_x_dir                             = true
y_driver_type                            = A4988
invert_y_dir                             = true
z_driver_type                            = A4988
invert_z_dir                             = true
e0_driver_type                           = A4988
invert_e0_dir                            = true

endstoppullups                           = on
x_max_endstop_hit_state                  = LOW
x_min_endstop_hit_state                  = LOW
y_max_endstop_hit_state                  = LOW
y_min_endstop_hit_state                  = LOW
z_max_endstop_hit_state                  = LOW
z_min_endstop_hit_state                  = LOW

#SOWFTWARE ENDSTOPS
max_software_endstops                    = on
max_software_endstop_x                   = on
max_software_endstop_y                   = on
max_software_endstop_z                   = on
min_software_endstops                    = on
min_software_endstop_x                   = on
min_software_endstop_y                   = on
min_software_endstop_z                   = on

# HOMING
x_home_dir                               = -1
z_home_dir                               = -1
y_home_dir                               = -1
z_after_homing                           = 10
z_clearance_for_homing                   = 4
z_min_probe_endstop_hit_state            = Z_MIN_ENDSTOP_HIT_STATE
homing_bump_mm                           = { 0, 0, 5 }
HOMING_BUMP_DIVISOR                      = { 3, 3, 5 }

# FANS
e0_auto_fan_pin                          = -1
extruder_auto_fan_speed                  = 255
extruder_auto_fan_temperature            = 50

# EXTRUDERS and TEMPERATURE CONTROL
extruders                                = 1
temp_sensor_0                            = 1
thermal_protection_hotends               = on
heater_0_mintemp                         = 5
heater_0_maxtemp                         = 300
extrude_mintemp                          = 200
prevent_cold_extrusion                   = on
max_heater_0_power                       = 192
bang_max                                 = MAX_HEATER_0_POWER

pidtemp                                  = on
pid_k1                                   = 0.95
pid_max                                  = MAX_HEATER_0_POWER
default_kp                               = 15.0
default_ki                               = 2.0
default_kd                               = 50.0

# BED HEATING
temp_sensor_bed                          = 1
thermal_protection_bed                   = on
bed_mintemp                              = 5
bed_maxtemp                              = 100
max_bed_power                            = 255
pidtempbed                               = off
default_bedKd                            = 10.00
default_bedKi                            = .023
default_bedKp                            = 305.4

# PREHEATS
preheat_1_label                          = "PLA"
preheat_1_temp_bed                       = 70
preheat_1_temp_hotend                    = 180
preheat_2_label                          = "ABS"
preheat_2_temp_bed                       = 110
preheat_2_temp_hotend                    = 240

[config:easythreed_ui]
lcd_language                             = en
EASYTHREED_K9_ET4000PLUS                 = on
easythreed_ui                            = on
custom_user_buttons                      = on
button1_desc                             = "Homing"
button1_gcode                            = "G28"
button1_hit_state                        = LOW
button1_pin                              = PC3
button1_when_printing                    = false
button2_desc                             = "Levelling Position 1"
button2_gcode                            = "G0 Z5\nG0 X0 Y0\nG0 Z0"
button2_hit_state                        = LOW
button2_pin                              = PC7
button2_when_printing                    = false
button3_desc                             = "Levelling Position 2"
button3_gcode                            = "G0 Z5\nG0 X0 Y100\nG0 Z0"
button3_hit_state                        = LOW
button3_pin                              = PC11
button3_when_printing                    = false
button4_desc                             = "Levelling Position 3"
button4_gcode                            = "G0 Z5\nG0 X100 Y100\nG0 Z0"
button4_hit_state                        = HIGH
button4_pin                              = PA2
button4_when_printing                    = false
button5_desc                             = "Levelling Position 4"
button5_gcode                            = "G0 Z5\nG0 X100 Y0\nG0 Z0"
button5_hit_state                        = HIGH
button5_pin                              = PA3
button5_when_printing                    = false

[config:host]
host_action_commands                     = on
emergency_parser                         = on
faster_gcode_parser                      = on
GCODE_QUOTED_STRINGS                     = on
gcode_case_insensitive                   = on
BINARY_FILE_TRANSFER                     = on
advanced_ok                              = on
host_keepalive_feature                   = on
default_keepalive_interval               = 2
serial_overrun_protection                = on
auto_report_position                     = on
auto_report_temperatures                 = on
extended_capabilities_report             = on
bufsize                                  = 4
tx_buffer_size                           = 128
block_buffer_size                        = 16
max_cmd_size                             = 96

[config:linear]
lin_advance                              = on
advance_k                                = 0.2
distinct_e_factors                       = off
volumetric_extruder_limit                = off
classic_jerk                             = off
default_ejerk                            = 2.0

[config:backlash]
backlash_compensation                    = on
measure_backlash_when_probing            = off
backlash_correction                      = 1.0
backlash_distance_mm                     = { 0.5, 0.5, 0 }
backlash_gcode                           = on
backlash_smoothing_mm                    = 0
