[config:base]
; Copy ini_use_config value to Marlin/config.ini to use
;ini_use_config                          = basic +host +debug @../config/examples/simulation/config.ini
ini_config_version                       = 02010300
string_config_h_author                   = "qw3rtrun"
config_examples_dir                      = "config/examples/simulation"

[config:basic]
MACHINE_UUID                             = "00000000-0000-0000-0000-000000000000"
CUSTOM_MACHINE_NAME                      = "MarlinSim"
motherboard                              = BOARD_SIMULATED
serial_port                              = 0
baudrate                                 = 250000
serial_port_2                            = 3
baudrate_2                               = 250000

sdsupport                                = on
eeprom_settings                          = on

x_bed_size                               = 200
x_driver_type                            = A4988
x_enable_on                              = 0
x_home_dir                               = -1
x_max_endstop_hit_state                  = HIGH
x_max_pos                                = X_BED_SIZE
x_min_endstop_hit_state                  = HIGH
x_min_pos                                = 0
y_bed_size                               = 200
y_driver_type                            = A4988
y_enable_on                              = 0
y_home_dir                               = -1
y_max_endstop_hit_state                  = HIGH
y_max_pos                                = Y_BED_SIZE
y_min_endstop_hit_state                  = HIGH
y_min_pos                                = 0
z_driver_type                            = A4988
z_enable_on                              = 0
z_home_dir                               = -1
z_max_endstop_hit_state                  = HIGH
z_max_pos                                = 200
z_min_endstop_hit_state                  = HIGH
z_min_pos                                = 0
z_min_probe_endstop_hit_state            = HIGH

reprap_discount_full_graphic_smart_controller = on
lcd_language                             = en
reverse_menu_direction                   = on
boot_marlin_logo_animated                = on
boot_marlin_logo_small                   = on
show_bootscreen                          = on
startup_commands                         = "M118 Sim Startup!"
use_big_edit_font                        = on
xyz_hollow_frame                         = on

[config:host]
bufsize                                  = 4
max_cmd_size                             = 96
block_buffer_size                        = 16
tx_buffer_size                           = 128
serial_overrun_protection                = on
host_keepalive_feature                   = on
NO_TIMEOUTS                              = off

#REPORTS and COMMUNICATION capabilities
host_action_commands                     = on
faster_gcode_parser                      = on
GCODE_QUOTED_STRINGS                     = on
gcode_case_insensitive                   = on
BINARY_FILE_TRANSFER                     = on
advanced_ok                              = on
extended_capabilities_report             = on
auto_report_temperatures                 = on
host_prompt_support                      = on
HOST_STATUS_NOTIFICATIONS                = on
HOST_PAUSE_M76                           = on
HOST_START_MENU_ITEM                     = on
HOST_SHUTDOWN_MENU_ITEM                  = on
eeprom_chitchat                          = off
m114_detail                              = on
EMERGENCY_PARSER                         = on
REALTIME_REPORTING_COMMANDS              = off
FULL_REPORT_TO_HOST_FEATURE              = on

[config:debug]
eeprom_boot_silent                       = on
pins_debugging                           = on
MARLIN_TEST_BUILD                        = off
MARLIN_DEV_MODE                          = off
BUFFER_MONITORING                        = off
